### PR TITLE
Kafka Windows dependencies.

### LINKED ISSUE #14: Kafka Dependencies for Windows
Kafka dependencies for Windows MSVC 14. Related to #13

### PR DESCRIPTION
**Pull request by LamarMoore**
Fixes #14
Dependencies for Kafka live listener added to third party repo.

To test:

* Run `[PathToThirdPartyFolder]/build-scripts/build-librdkafka`
* check the `[PathToThirdPartyFolder]/bin` and `[PathToThirdPartyFolder]/lib` for the following files:
```
librdkafka.dll/pdb
librdkafka_D.dll/pdb
librdkafkacpp.dll/pdb
librdkafkacpp_D.dll/pdb
librdkafka.lib/librdkafka_D.lib
librdkafkacpp.lib/librdkafkacpp_D.lib
```

Further tests to ensure functionality with the mantid codebase can be found [here](https://github.com/ScreamingUdder/mantid/pull/5)

### CODE REVIEW

**Comment by martyngigg** [comment]
@LamarMoore This looks good. It's good we've managed to keep the original source clean and only patch the VS files.

One question remains. Is this the right place for the flatbuffers dependency? For our purposes I was under the impression that we only needed the single `flatbuffers.h` header and I was going to suggest we actually put that alongside the KafkaListener in the Mantid code. I think this will be easier to maintain rather than forcing the other platforms to generate dev packages for a single header. @matthew-d-jones Any thoughts on this?

**Comment by matthew-d-jones** [comment]
Yes, the header should be all that is required. It is at `Framework/LiveData/src/ISIS/private/Kafka/Schema/flatbuffers/flatbuffers.h` in the development branch.
The only occasion that anything else is required is when the schema changes and the headers need to be regenerated. We should make sure the location of the schema repository and how to regenerate the headers is documented somewhere.

**Comment by LamarMoore** [comment]
@martyngigg Ok I can remove the flatbuffers install

**Comment by martyngigg** [comment]
This looks good. I've built and run the unit tests against both release and debug libraries and everything seems fine.

**Comment by martyngigg** [comment]
I'm not going to merge this right now but it should be merged once [ScreamingUdder:mantid](/ScreamingUdder/mantid/tree/isis_kafka_listener) is merged to  [mantidproject:mantid].

**Pull request merged**
