### PR TITLE
Add PS2EXE PowerShell script

### PR DESCRIPTION
**Pull request by DTasev**
Adds the PS2EXE PowerShell script used by https://github.com/mantidproject/mantid/pull/23809 to create an executable for the Mantid Workbench.

Source of script: https://gallery.technet.microsoft.com/scriptcenter/PS2EXE-GUI-Convert-e7cb69d5

### CODE REVIEW

**Comment by martyngigg** [comment]
As its an executable can we move this to `bin`. The `build-scripts` directory is meant for scripts that build the libraries in this repository.

**Comment by DTasev** [comment]
It's now been moved to `bin/ps2exe.ps1`

**Comment by martyngigg** [comment]
Thanks.

**Comment by martyngigg** [comment]
Could we also add a ps2exe.txt with a short description of it and where it came from for future reference?

**Comment by DTasev** [comment]
File description added and commits squashed into a single one

**Pull request merged**
