### PR TITLE
Add bayesfitting libraries

### PR DESCRIPTION
**Pull request by StephenSmith25**
Add a pip install of the bayesfitting libraries

I'm not sure how to test it at the moment as I'll need to update the indirect import file in mantid.

But running `import bayesfitting` should work

### CODE REVIEW

**Comment by martyngigg** [comment]
I just had a question about the `QLwat` library in bayesfitting. Did we want to wait for that and install it here too or is it too early for that?

**Comment by StephenSmith25** [comment]
I guess there's no issue with doing it all now, I was just being a little cautious. I was thinking maybe its good to test this out first and make sure everything is in order.  I've got a PR up in mantid changing the indirect imports, so this should be testable soon once that is merged. If it all works we can also delete all the *.pyd files we ship with mantid and also the gfortran dll.

**Comment by martyngigg** [comment]
Sounds good. I'll test/review this PR in a second.

**Review by martyngigg — APPROVED** [review]
This works as expected and I can import the bayesfitting package and submodules 👍🏻

**Comment by martyngigg** [comment]
We can use `8fc63456a00da9d734415f7838773b1c20bcbbe3` now in the `Bootstrap.cmake` to pull the updates into `mantid`.

**Pull request merged**
