### PR TITLE
JSON updated to version 1.8.1

### LINKED ISSUE #21: Update jsoncpp to v 1.8.1
This avoids bundling a second version for Paraview

### PR DESCRIPTION
**Pull request by LamarMoore**
Fixes #21 
Json has been updated for windows builds to 1.8.1.

### CODE REVIEW

**Comment by martyngigg** [comment]
The changes look fine at this level.

Can you follow the instructions in the main [README](/mantidproject/thirdparty-msvc2015/README.md) and verify that this works with Mantid before we merge it for everyone?

**Comment by LamarMoore** [comment]
I built this into Mantid on my machine by changing the commit in Boostrap.cmake. The build completed successfully.

**Comment by martyngigg** [comment]
@LamarMoore Thanks.

@quantumsteve Does this need to be updated at the same time that we update ParaView or will Mantid still build with ParaView as it currently stands if we merge this now?

**Comment by LamarMoore** [comment]
@martyngigg  do I need to make a PR in the mantid repo to point at this commit?

**Comment by martyngigg** [comment]
@LamarMoore It depends what @quantumsteve says in response to my question above.

**Comment by quantumsteve** [comment]
@LamarMoore @martyngigg I think we're better off making this change at the same time as ParaView 5.4. The two versions of jsoncpp aren't binary compatible so mixing them is a bit risky.

**Comment by martyngigg** [comment]
@quantumsteve That makes sense. In that case we just need to ensure that we update the `THIRD_PARTY_GIT_SHA1` in [](https://github.com/mantidproject/mantid/blob/77b6d91d074702660515b1f1a19bee105485f9ac/buildconfig/CMake/Bootstrap.cmake#L13) in the same PR that we update ParaView.

**Comment by martyngigg** [comment]
Merged in line with mantidproject/mantid#19941

**Pull request merged**
